### ISSUE TITLE
Falsche Web-Adresse

### ISSUE THREAD

**Issue by pyramidenkoenig** [freifunkMUC/logo_merchandise_ci#6]
muenchen.freifunk.net (siehe "Hallo Nachbar" Flyer löst nicht auf, wieso eigentlich? 
Vll. abändern.

**Comment by pyramidenkoenig** [comment]
Problem an die leute von Freifunk gemeldet vor einigen wochen. Bisher keine reaktion.

**Comment by awlx** [comment]
Domain wieder erreichbar.
