### ISSUE TITLE
Fehlendes SSL-Zertifikat für URL auf Hallo Nachbar-Flyer

### ISSUE THREAD

**Issue by mayrstefan** [freifunkMUC/logo_merchandise_ci#7]
Analog zu #6: Das Flyer Hallo Nachbar enthält die den Hinweis auf muenchen.freifunk.net. Die Domain ist zwar prinzipiell erreichbar, man bekommt aber einen Fehler weil die meisten Browser inzwischen per Default https machen aber das Zertifikat nicht zu dieser Domain passt. Man müsste das Let's Encrpyt-Zertifikat auch für die andere Domain mit ausstellen lassen oder die Domain auf dem Flyer anpassen.

**Comment by istrator2** [comment]
Zertifikat ist jetzt übrigens wieder gültig.
Das Issue wäre damit gelöst. :)

**Comment by mayrstefan** [comment]
https://muenchen.freifunk.net/ funktioniert jetzt wie erwartet
